language: ruby
rvm:
  - 2.1.0
  - 2.2.0
env:
  - REDMINE_VERSION=3.2.0 VERBOSE=yes
  - REDMINE_VERSION=3.1.3 VERBOSE=yes
script:
  - export PLUGIN=redmine_scrum_cards
  - export WORKSPACE=$(pwd)/workspace
  - export PATH_TO_PLUGIN=$(pwd)
  - export PATH_TO_REDMINE=$WORKSPACE/redmine
  - mkdir $WORKSPACE
  - bash -x ./.travis-init.sh -r || exit 1
  - bash -x ./.travis-init.sh -i || exit 1
  - bash -x ./.travis-init.sh -t || exit 1
  - bash -x ./.travis-init.sh -u || exit 1